### ISSUE TITLE
Generex random method does not generate last item in regex range of numbers

### ISSUE THREAD

**Issue by ciditri** [mifmif/Generex#10]
If the regex expression is a range of numbers, the random() method of Generex class does not ever return the last item in the interval.

E.g.:
new Generex("[0-1]").random(); // will never return value 1, only 0;

**Comment by mifmif** [comment]
It was an issue while calculating possible element number , i've just commit a correction. you can checkout the source code .

**Comment by ciditri** [comment]
Thanks!
