### ISSUE TITLE
Anchors aren't taken into account

### ISSUE THREAD

**Issue by chriszinkula** [mifmif/Generex#20]
If you use a regex such as

`^[a-z]$`

You will get results of
```
^a$
^b$
^c$
...
^z$
```

The anchors likely should be stripped before processing as you would expect to just get all the lowercase letters of the alphabet instead.

**Comment by mifmif** [comment]
In convention, those anchors are used to match the beginning/end of a matched string. when we use  Generex we try instead to generate matched strings. Thus, it doesn't seem useful to use those anchors with Generex as meta-character to do what they do with a pattern matcher. then they are presented in Generex as normal character not  as meta-character.

**Comment by JonasJurczok** [comment]
Ah.. At first I wanted to open exactly this ticket but with this explanation it totally makes sense.

Thank you for the library. It really makes my life _much_ easier right now :)
