### ISSUE TITLE
Allow to pass seed to controll randomess

### ISSUE THREAD

**Issue by PascalSchumacher** [mifmif/Generex#23]
Thanks for providing this library!

It would be nice if it was possible to pass a seed, similar to `new Random(long seed)`. This would allow to repeat the exact generated results, e.g. to repeat test with the same data.

Maybe this is already possible and I just overlooked it?

Thanks,
Pascal

**Comment by mifmif** [comment]
Hi,
currently this feature is not available, i think it would be helpful for users and I will  added it to the library , I've added some code in my local repository that add this feature, I will push it in the next release after some tests.

**Comment by PascalSchumacher** [comment]
Great! :+1: 

Looking forward to the next release.

Thank you very much!  :)

**Comment by PascalSchumacher** [comment]
Hi mifmif,

a release with the features would be greatly appreciated. :)

If there is anything I can do to help, just let me know.

Thanks,
Pascal

**Comment by mifmif** [comment]
I plan to push a set of modifications all together in the next release , this feature will be included , I will comment and close this request when the next release become available( before the next week).

**Comment by mifmif** [comment]
This feature is now supported by using the new method Generex.setSeed().

**Comment by PascalSchumacher** [comment]
Thank you very much! :)
