### ISSUE TITLE
Random with limit doesn't work

### ISSUE THREAD

**Issue by kilaka** [mifmif/Generex#25]
Generex generex = new Generex("^(.*?=.{8,})(?=.*[\\d])(?=.*[\\W]).*$");
String password = generex.random(20, 20);

Result: 494 chars string.

**Comment by carlphilipp** [comment]
[\d((?!11)\d{2})((?!55501)\d{7}) does not work either. ?! is not supported ?

**Comment by mifmif** [comment]
Issue Fixed in version 1.0.2.
