### ISSUE TITLE
Simple random() brings Exception

### ISSUE THREAD

**Issue by HenningL** [mifmif/Generex#30]
Using java 8.

Simply call random() brings Exception in Generex line 278 with random(nextInt(0)). Since the randomTransition.getMax and randomTransition.getMin are the same (value "i")

Workarounding this. Also the rootNode is not present before asking a value so asking the size before asking the value leads to NPE

        static{
		try {
			buildMethod = Generex.class.getDeclaredMethod("buildRootNode");
			buildMethod.setAccessible(true);
		} catch (NoSuchMethodException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SecurityException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		    }
	        }
               Generex generex = new Generex(regex);
		try {
			buildMethod.invoke(generex);
		} catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException e) {
			e.printStackTrace();
		}
		
		int index = new Random(generex.matchedStringsSize()).nextInt();
		
		String generatedValue = generex.getMatchedString(index);

**Comment by thc202** [comment]
The NPE should be fixed (#13) in the latest version (as of writing, 1.0.0).

**Comment by mifmif** [comment]
@HenningL  could you please specify the version used , and a code example to reproduce the issue, I think that this NPE is already fixed as @thc202 said.

**Comment by HenningL** [comment]
was the one i found in maven central, think was 0.0.1. I searched mvn central and saw there's a 1.0.2, i will try this one. Sorry for the old version bug report. Was the version i found first in mvnrepo googling it.

**Comment by mifmif** [comment]
Ok, if the problem persists with the current version you can re-open the issue.
