### ISSUE TITLE
Tags latest releases in Maven Central

### ISSUE THREAD

**Issue by thc202** [mifmif/Generex#31]
Would be possible to have the tags of the (latest) releases (e.g. 1.0.1, 1.0.2) available in Maven Central?

**Comment by mifmif** [comment]
at this time the latest release is 1.0.1

**Comment by thc202** [comment]
Right, what I'm asking for is the tag of that (and previous) release. The current tags [1] stop at version 1.0.0.

[1] https://github.com/mifmif/Generex/tags

**Comment by thc202** [comment]
Thanks for pushing the tag :)
