### ISSUE TITLE
Positive and negative lookahead

### ISSUE THREAD

**Issue by dovidkopel** [mifmif/Generex#32]
For complex patterns like:
`((?!000)(?!666)(?:[0-6]\\d{2}|7[0-2][0-9]|73[0-3]|7[5-6][0-9]|77[0-2]))-((?!00)\\d{2})-((?!0000)\\d{4})`

the `?!` character seem to be interpreted literally, it would be nice to have support for all of the supported characters that Java support (https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html)

**Comment by mifmif** [comment]
Hi,
Unfortunately the used library ([automaton](http://www.brics.dk/~amoeller/automaton)) has some limitations, one of them is that it doesn't support the [look-ahead and look-behind](http://www.regular-expressions.info/lookaround.html)  assertions  . So they will not be interpreted as assertion in your regular expression.
