### ISSUE TITLE
 Hello, can you add a function to support Chinese generation

### ISSUE THREAD

**Issue by ErinWj** [mifmif/Generex#35]

**Comment by ErinWj** [comment]
I want to use Generex generate Chinese，the rex is [u4e00-u9fa5]，could you help me？

**Comment by thc202** [comment]
That should work already:
```Java
public static void main(String[] args) {
    Generex generex = new Generex("[\u4e00-\u9fa5]");
    System.out.println(generex.random());
}
```
outputs, for example:
`橧`

**Comment by ErinWj** [comment]
ok,thank you~

**Comment by adenix** [comment]
Chinese def works. I have a problem where I don't want Chinese but for some reason I get it...
