### ISSUE TITLE
Positive Lookahead

### ISSUE THREAD

**Issue by adenix** [mifmif/Generex#36]
I have the following Generex:

<pre>
return
    new Generex("(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9$@!%*#?&])[A-Za-z0-9$@!%*#?&]{6,10}")
        .random();
</pre>

My result is this:

?=㉲h⫗]"?mmfF遛A 葊3ꦠu!o?쇄x8rp㥌䜂廘>N#溦꼲NZcMx熚d?'੫
jWu㞠䰙â[w?	鰭;f?騐灝峱^栀㡓곖pYhPx\
趪^쌒UdeOb7xl>f&# ⪫p풵vRw/*`s?6<b?焹蠢Mg?乭s?=A:F@좽?8NR@FV&2U5ꇖ⧉柭垚6+꧿펊/N?=(;!*嗼!V:!^"!ߚ"'4=";$!1b*筍/'0D*&v"@c`%[?<,!BCy@#e닳*:??";뽴.'5?*k-%C("!""!"*$"!t@"坓+:,匓!;"8㡡:&"2*5#!*"%Z$(<$礯(!긿;>#"77>&!;"&*,+<"@CQ*%*)"!*$#)+ᗗ'+$8@Z)"%'""<!#)@.*/%_6*,*^?)*3"@=(""!N$$1,僰)@&!*!a&

Is looks like Positive Lookahead isn't supported. Can this be implemented?

**Comment by mifmif** [comment]
Unfortunately the positive/negative look ahead and look behind are not supported, check this #32
