### ISSUE TITLE
Pipe with empty character doens't work

### ISSUE THREAD

**Issue by jimmbraddock** [mifmif/Generex#38]
If I want to use regex as `(a|)` then it doesn't work, although it is proper expression.
`new Generex("(a|)").random()` generate error and expecting `)` at the end.

Also `(a)?` always generate `a` and never empty string.

**Comment by mifmif** [comment]
when using the pipe meta-char , you have to put non-empty char in each side, ex : (a|b) , 
in your expression , i see that you want 'a' or nothing, in this case you can just set "(a)?"
