### ISSUE TITLE
^ and $ are used as a normal characters

### ISSUE THREAD

**Issue by momoendo** [mifmif/Generex#41]
It seems that `^` and `$` are used as normal characters but actually they assert position at start or end of the string. 

As a result the following code

`new Generex("^A$").random()` 

will generate `^A$`, instead of just `A`.

**Comment by nmargaritis** [comment]
I noticed the same problem. Any plans for this?

**Comment by mifmif** [comment]
You don't need to use ^and $ in the beginning and the end of the regex , they are considered as normal character not as meta-character.

**Comment by momoendo** [comment]
But aren't those regular expression anchors? Why would you treat them as normal characters?

**Comment by mifmif** [comment]
generex is used to generate string based on the passed regex, so the pattern that you will pass to generex is used as it is to generate string, and you don't need to specify the beginning and the end of your pattern.

**Comment by momoendo** [comment]
I'm not specifing the beginning or end of the pattern, I specify a location within the string on which the pattern is used on.

There is a difference between the regex "^test$" and "test". Generex might generate the same string from both at the end and that would be fine, but it should not just treat them as normal characters. Right now, the user has to modify its valid regex.

You said it yourself: "based on the passed regex". And "^test$" is a valid regex that does NOT match with the currently generated string "^test$".

**Comment by SergejFrank** [comment]
i have the same issue with this libary.  The start and endig tags are mandatory in some expressions.
i wanted to generate a password that matches my pattern. But i need the meta characters for that.

do you consider to implement them?
