### ISSUE TITLE
Values given by iterator have duplicates

### ISSUE THREAD

**Issue by ucassh** [mifmif/Generex#7]
In Your example we have:
        // it print 0a 0b 0c 0e 0ee **0e 0e** 0f 0fe **0f 0f** 0g 0ge **0g 0g** 1a 1b 1c 1e
        // 1ee **1e 1e** 1f 1fe 1f 1f 1g 1ge **1g 1g** 2a 2b 2c 2e 2ee **2e 2e** 2f 2fe **2f 2f** 2g
        // 2ge **2g 2g** 3a 3b 3c 3e 3ee **3e 3e** 3f 3fe **3f 3f** 3g 3ge **3g 3g** 1ee
bold - duplicates; 

When I run sample code from [how-to](https://github.com/mifmif/Generex#how-to-use-it-) I get:
                        0a 0b 0c 0e 0ee 0e 0e 0f 0fe 0f 0f 0g 0ge 0g 0g 1a 1b 1c 1e 
           1ee 1e 1e 1f 1fe 1f 1f 1g 1ge 1g 1g 2a 2b 2c 2e 2ee 2e 2e 2f 2fe 2f 2f 2g 
           2ge 2g 2g 3a 3b 3c 3e 3ee 3e 3e 3f 3fe 3f 3f 3g 3ge 3g 3g 

but when You loop over list from getAllMatchedStrings()
```
        // Generate all String that matches the given Regex.
        List<String> matchedStrs = generex.getAllMatchedStrings();
        for (String string : matchedStrs) {
			System.out.print(string + " ");
	}
```
You will see a little bit different result
                     0a 0b 0c 0e 0ee **0ef 0eg** 0f 0fe **0ff 0fg** 0g 0ge **0gf 0gg** 1a 1b 1c 1e 
          1ee **1ef 1eg** 1f 1fe 1ff 1fg 1g **1ge 1gf** 1gg 2a 2b 2c 2e **2ee 2ef** 2eg 2f **2fe 2ff** 2fg 2g
          2ge **2gf 2gg** 3a 3b 3c 3e 3ee **3ef 3eg** 3f 3fe **3ff 3fg** 3g 3ge **3gf 3gg** 

bold - correct values

**Comment by mifmif** [comment]
fixed in version 0.0.4
